### ISSUE TITLE
text does not want to disappear

### ISSUE THREAD

**Issue by Mavrinn** [RohitKotiveetil/UnrealEngine--DamageDisplaySystem#1]
Hello,

You have built a super combat notifier however, I have a problem when migrating your project. I use unreal engine 4.23.0
During the migration, the nodes were not "understood", I took over your project and repaired it by hand.

Now the text is displayed well but it doesn't want to disappear. Where should I look?
I thought you were using a "timer" to display the text but I can't find it.
You can see it on the picture
![Screenshot_3](https://user-images.githubusercontent.com/35135877/65376497-bf11be80-dca0-11e9-820d-0d6df6e66cd2.png)

**Comment by Mavrinn** [comment]
I have migrated for the third time and it worked!

**Comment by RohitKotiveetil** [comment]
Hi there, I haven't gotten around to testing it in 4.23 and hence wasn't aware of the issue you mentioned. In any case, glad to hear that you got it working. Have fun!
